site_name: 'python-app'
site_description: 'Main documentation for Python App'
repo_url: https://github.com/xcirel/python-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: 'docs/index.md'