name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set short git commit SHA
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: xcirel/python-app:${{ env.COMMIT_ID }}
  cd:
    needs: [ci] 
    runs-on: self-hosted
    steps:
      - 
        name: Install ArgoCD
        shell: bash
        run: |
          curl -kssL -o https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - 
        name: ArgoCD app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
          argocd app sync python-app